### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by YoSiJo** [ismvru/zbx-tmplt-pbs#4]
I would like to use the template both privately and in a professional context. For the latter, however, it is of course essential that a license is known.
Since I don't know how well the topic is known, I personally think the AGPL is the best, because it ensures that companies that develop the software have to give it back to the community.

**Comment by ismvru** [comment]
@YoSiJo 
Hello! I apologize for not answering for a long time. I'm thinking of using the **0BSD** license as the most permissive. #5
Any objections?

**Comment by YoSiJo** [comment]
Unexpected choice ;)
I hadn't heard of the 0BSD until now.
I openly admit that I'm not a fan of licenses without copyleft, but that's a personal preference. It would also be professionally usable and therefore suitable for my case.
But I want to give you a hint, both Zabbix and Proxmox are licensed under AGPL-3.0.

**Comment by ismvru** [comment]
Hi! Thanks for the tip. I wanted to use the BSD0 license as the most permissive of those I know (not counting exotic ones like WTFPL).
I read the text of AGPL-3, I liked it. Perhaps I will add this license :)

**Comment by ismvru** [comment]
Merged #5 with AGPL-3 and copyright lines.
